### PR TITLE
Adding new feature to provide spacing around the drawer.

### PR DESCRIPTION
**Pull request by ratulSharker**
Actually i'm working on a project which require iOS 10 Map like bottom drawer. Thanks to pulley which covers most part of this requirement. According to the app design, it requires left and right spacing between drawer, where pulley does not support these spacing any of those delegates. I have introduced a delegate method `drawerEdgeInset` in `PulleyDrawerViewControllerDelegate` to provide these values around the drawer. Following is a list which i have completed. Default value is used from `kPulleyDefaultDrawerInset` constant.

Following is the design i tried to achieve with pulley.
<a href="https://imgur.com/a/PRQBZxo">Design</a>
 
- [x] considering the left and right value of the `drawerEdgeInset`.
- [ ] considering the top and bottom value of the `drawerEdgeInset`.
- [ ] Updating the **Customizing the drawer** section of README.md.

### CODE REVIEW

**Comment by brendan09** [comment]
This already works on iOS 11.0+ using the standard iOS safe areas API. As a result, I don't believe adding an additional non-standard method of insetting the drawer is a wise decision (even though the current method doesn't support older versions of iOS).

If you need to support older versions of iOS, my recommendation is:

1. Set the drawer corner radius to 0.0
2. Set the drawer shadow opacity to 0.0
3. Set the drawer visual effect view to nil
4. Set your view controller's background color to clear
5. Implement your drawer view controller to provide its own background view that's inset, and then add rounded corners and a shadow to that view. That will accomplish what you're looking for using the stock version of Pulley and doesn't require a non-standard version of inset support.

**Comment by ratulSharker** [comment]
Thanks for you suggestion. As per your suggestion, i did following in the pulley demo project

1. Set the drawer corner radius, shadow opacity and shadow radius to 0.0
2. Introducing a left & right spacing to drawer.
3. Set the drawer view controller views color to clear color.

Ignoring the drawer opening background shadow, it does not achieve what you stated. Regarding setting the background color to clear color, the background is not set so.

<a href="https://imgur.com/a/2N8IbQ8">Configuration of drawer</a>
<a href="https://imgur.com/a/vqqv7cp">Customizing the drawer</a>
<a href="https://imgur.com/a/0wrLfwW">Output</a>

NB: i didn't understand the point  (3 .Set the drawer visual effect view to nil). Please explain how to do so.

**Comment by brendan09** [comment]
You need to set the visual effect view to nil.

On Pulley, assign this property nil: drawerBackgroundVisualEffectView

**Comment by ratulSharker** [comment]
not working.

**Comment by brendan09** [comment]
What does it look like when you do that? I’ve tried it and it does remove the blur background.

**Pull request closed without merging**
