### PR TITLE
Add closed position

### PR DESCRIPTION
**Pull request by mmadjer**
Let's add a closed position so that you can have it initially closed and reveal when needed or
close it when not needed anymore.

### CODE REVIEW

**Comment by ericlewis** [comment]
+1

**Comment by Alex293** [comment]
Definitely a nice to have ! Do you need to initialise the contained vc anyway with you pr or can you let it nil while the pulley is closed ?

**Comment by brendan09** [comment]
I'm still debating whether or not I think this is a good change conceptually. This is modeled after Apple Maps and it's UI, which doesn't support 'closed'. I'm inclined to think that this lends itself to bad UI patterns. However, it's certainly open for conversation and if there's an overwelming opinion that I should merge it then I will.

**Comment by ericlewis** [comment]
My only arguement about merging it is that there doesn't seem to be a way to set it as a default position when initializing the PulleyViewController. That said, our use case is pretty simple for why we want it. We allow users to tap a pin or cluster of pins from the map view which will then bring up either collapsed or expanded modes depending on the type of pin selected. When moving around the map or not interacting with the pins, we see no reason to show the drawer. The drawer has utility slightly beyond imitating maps too, as I'm using it in a different context entirely for a different app. No maps or table view involved. It's a useful addition, but, I would like to see more customization along with it like I listed. The current solution we use now is to closed it on viewWillAppear, but that also makes autolayout act strange even though it's not animated.

**Pull request merged**
